### ISSUE TITLE
Some correction using swift

### ISSUE THREAD

**Issue by AlainL88** [tylyo/APLineChart#5]
Hi there is some problem with the line 
    override func touchesMoved(touches: NSSet, withEvent event: UIEvent) {
and 
    override func touchesEnded(touches: NSSet, withEvent event: UIEvent) {
I use your project in swift and when I add it I need to change the lines above to the lines below:
    override func touchesEnded(touches: Set<NSObject>, withEvent event: UIEvent) {
    override func touchesMoved(touches: Set<NSObject>, withEvent event: UIEvent) {
and then instead of 
        if let markerLine = lineMax? {
and 
        if let markerLine = lineMin? {

I use 
        if let markerLine = lineMax {
        if let markerLine = lineMin {

**Comment by tylyo** [comment]
thanks, updated.

**Comment by AlainL88** [comment]
Thank's to You for Your great job. :+1:
